# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='picture',
            field=models.CharField(default='', max_length=200),
        ),
    ]
